# Generated by Django 3.0.5 on 2020-04-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='document',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
