# Generated by Django 3.0.5 on 2020-04-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200419_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='conf_num',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
