# Generated by Django 3.0.5 on 2020-04-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200419_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='conf_num',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
