# Generated by Django 3.0.5 on 2020-04-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200419_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='conf_num',
        ),
        migrations.RemoveField(
            model_name='student',
            name='confirmed',
        ),
    ]
